; Supervisor config file for program(s)
; copy this file into /etc/supervisor/conf.d/ folder

[program:ULE-Ion-pump-to-influxdb]
command=/home/imaq-pi03/Projects/ULE-Ion-pump-to-influxdb/Startup_bash
environment=PYTHONUNBUFFERED=1 ; let stdout logged in real time for python app
user=imaq-pi03
autostart=true
autorestart=true
stdout_logfile=/etc/supervisor/logs/ULE-Ion-pump-to-influxdb_out.log
stderr_logfile=/etc/supervisor/logs/ULE-Ion-pump-to-influxdb_err.log